Rss\RecommendBundle\Entity\LoginUser:
    type: entity
    table: login_user
    uniqueConstraints:
        user_name:
            columns:
                - user_name
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            nullable: false
            length: 32
            fixed: false
            comment: ''
            column: user_name
        mailAddress:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
            column: mail_address
        twitterAccount:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
            column: twitter_account
        password:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
