Rss\RecommendBundle\Entity\LoginUser:
    type: entity
    table: login_user
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        userName:
            type: string
            length: 255
            column: user_name
        mailAddress:
            type: string
            length: 255
            column: mail_address
        twitterAccount:
            type: string
            length: 255
            column: twitter_account
        password:
            type: string
            length: 255
    lifecycleCallbacks: {  }
