Rss\RecommendBundle\Entity\RssData:
    type: entity
    table: rss_data
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        url:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: URL
        synonym:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: Synonym
        similarurl:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: SimilarURL
    lifecycleCallbacks: {  }
