Rss\RecommendBundle\Entity\RssUrl:
    type: entity
    table: rss_url
    uniqueConstraints:
        user_id:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        rssUrl:
            type: string
            nullable: true
            length: 1000
            fixed: false
            comment: ''
            column: rss_url
    manyToOne:
        user:
            targetEntity: LoginUser
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
