Rss\RecommendBundle\Entity\UrlGroup:
    type: entity
    table: url_group
    indexes:
        url_group_group_id:
            columns:
                - group_id
        url_group_url_id:
            columns:
                - url_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    manyToOne:
        group:
            targetEntity: UrlGroupUser
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                group_id:
                    referencedColumnName: id
            orphanRemoval: false
        url:
            targetEntity: Url
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                url_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
