Rss\RecommendBundle\Entity\UrlGroup:
    type: entity
    table: url_group
    indexes:
        url_group:
            columns:
                - url_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        urlGroup:
            type: string
            nullable: true
            length: 30
            fixed: false
            comment: ''
            column: url_group
    manyToOne:
        url:
            targetEntity: Url
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                url_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
